# Generated by Django 5.0.6 on 2024-07-21 10:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_morning', models.BooleanField(default=False)),
                ('is_noon', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('booked', 'booked'), ('completed', 'completed'), ('doctor_blocked and cancelled', 'doctor_blocked and cancelled')], default='active', max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default='MC0001', max_length=10, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(default=datetime.date(2024, 12, 2))),
                ('status', models.CharField(blank=True, choices=[('confirmed', 'confirmed'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('cancelled_by_admin', 'cancelled_by_admin')], default='confirmed', max_length=100, null=True)),
                ('shift', models.CharField(blank=True, default='morning', max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('location', models.CharField(blank=True, default='kozhikode', max_length=200, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.available')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.CharField(blank=True, max_length=5, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
    ]
